### ISSUE TITLE
which part in this project is responsible for program slicing?

### ISSUE THREAD

**Issue by cyxin577** [kaist-ina/Extractocol_public#7]
if I only want to  use this project to implement backward/forward slicing, what should I do with these package/methods? Thanks for  your reply.

**Comment by cyxin577** [comment]
```
[E][12:34:03] StubMethodMap has been evaluated and serialized.
Exception in thread "main" java.lang.NullPointerException
	at ObfuscationSolver.MappingTable.filter1(MappingTable.java:112)
	at ObfuscationSolver.MappingTable.solve(MappingTable.java:126)
	at ObfuscationSolver.SolverCaller.M(SolverCaller.java:76)
	at extractocol.common.helper.InvokeHelper.methodDeobfuscation(InvokeHelper.java:92)
	at extractocol.common.trackers.tools.ArgToVEL.doesContainTargetMethod(ArgToVEL.java:100)
	at extractocol.frontend.MyBackwardInfoflow.scanMethodForSourcesSinksForArgTracking(MyBackwardInfoflow.java:1030)
	at extractocol.frontend.MyBackwardInfoflow.runAnalysis(MyBackwardInfoflow.java:380)
	at extractocol.frontend.MyBackwardInfoflow.computeInfoflow(MyBackwardInfoflow.java:160)
	at extractocol.frontend.MySetupApplication.runInfoflow(MySetupApplication.java:845)
	at extractocol.frontend.MyTest.runAnalysis(MyTest.java:668)
	at extractocol.frontend.MyTest.main(MyTest.java:246)
	at extractocol.common.trackers.tools.ArgToVEL.callFrontend(ArgToVEL.java:199)
	at extractocol.common.trackers.tools.ArgToVEL.M(ArgToVEL.java:83)
	at extractocol.common.trackers.ImplicitCallEdgeTracker.M(ImplicitCallEdgeTracker.java:54)
	at extractocol.tester.Extractocol.Extractocol_ImplicitCallEdgeTracker(Extractocol.java:68)
	at extractocol.tester.Extractocol.main(Extractocol.java:34)
```
By the way, I can't run it successfully, it reports errors like this. I debug it and find that the member variables( _map) in the MappingTable.java is null. 
```
 
private static HashMap<String, HashSet<OriginCandidate>> loadtable(String appname)
    {
        Kryo kryo = new Kryo();
        Input input = null;
        HashMap<String, HashSet<OriginCandidate>> existmap = null;
        try {
            File f = new File(Constants.getObfsPath());

            if (f.exists()) {
                input = new Input(new FileInputStream(Constants.getObfsPath()));
                existmap = kryo.readObject(input, HashMap.class);
                input.close();
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return existmap;
   }
    
```

thankyou!

**Comment by cyxin577** [comment]
This problem has been solved, check the main method in SolverCaller.java, find that _map should be loaded as args[0]
 ```
public class SolverCaller {
...
public static void main (String args[])
    {
        ...
        //load table
        MappingTable mt = new MappingTable();
        mt.setmap(loadtable(args[0]));
        ...
    }
}
```
or add condition in MappingTable.java
```
public class MappingTable implements java.io.Serializable {
    static HashMap<String, HashSet<OriginCandidate>> _map = new HashMap<>();
    public void setmap(HashMap<String, HashSet<OriginCandidate>> map)
    {
        if (map != null)//add here
            _map = map;
    }
}
```
